# Generated by Django 6.0.5 on 2026-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="게임명")),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="평점"),
                ),
                (
                    "players_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최소 인원"
                    ),
                ),
                (
                    "players_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최대 인원"
                    ),
                ),
                (
                    "play_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="플레이 시간(분)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="게임 설명")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("초급", "초급"), ("중급", "중급"), ("고급", "고급")],
                        max_length=10,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=100, verbose_name="출판사"),
                ),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="디자이너"
                    ),
                ),
                (
                    "bgg_id",
                    models.IntegerField(blank=True, null=True, verbose_name="BGG ID"),
                ),
                (
                    "bgg_rank",
                    models.IntegerField(blank=True, null=True, verbose_name="BGG 순위"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="카테고리"
                    ),
                ),
                (
                    "mechanism",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="메커니즘"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "reviews",
                    models.JSONField(blank=True, default=list, verbose_name="리뷰"),
                ),
            ],
            options={
                "verbose_name": "보드게임",
                "verbose_name_plural": "보드게임 목록",
                "db_table": "boardgame",
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="CrimeScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="게임명")),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="평점"),
                ),
                (
                    "players_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최소 인원"
                    ),
                ),
                (
                    "players_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최대 인원"
                    ),
                ),
                (
                    "play_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="플레이 시간(분)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="게임 설명")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("입문", "입문"), ("중급", "중급"), ("고급", "고급")],
                        max_length=10,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "series",
                    models.CharField(blank=True, max_length=100, verbose_name="시리즈"),
                ),
                (
                    "maker",
                    models.CharField(blank=True, max_length=100, verbose_name="제작"),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=100, verbose_name="출판사"),
                ),
                (
                    "publisher_kr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="국내 출판사"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "reviews",
                    models.JSONField(blank=True, default=list, verbose_name="리뷰"),
                ),
            ],
            options={
                "verbose_name": "머더미스터리",
                "verbose_name_plural": "머더미스터리 목록",
                "db_table": "crimescene",
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="Escape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="게임명")),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="평점"),
                ),
                (
                    "players_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최소 인원"
                    ),
                ),
                (
                    "players_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="최대 인원"
                    ),
                ),
                (
                    "play_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="플레이 시간(분)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="게임 설명")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("하", "하"), ("중", "중"), ("상", "상")],
                        max_length=10,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=50, verbose_name="지역"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="브랜드"),
                ),
                (
                    "theme",
                    models.CharField(blank=True, max_length=100, verbose_name="테마"),
                ),
                (
                    "fear_level",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="공포도(0~5)"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "reviews",
                    models.JSONField(blank=True, default=list, verbose_name="리뷰"),
                ),
            ],
            options={
                "verbose_name": "방탈출",
                "verbose_name_plural": "방탈출 목록",
                "db_table": "escape",
                "ordering": ["-rating"],
            },
        ),
    ]
