# Generated by Django 6.0.5 on 2026-05-15 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="세션 이름"
                    ),
                ),
                (
                    "players",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="인원 수"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planner_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "플래너 세션",
                "db_table": "planner_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("boardgame", "보드게임"),
                            ("escape", "방탈출"),
                            ("murdermystery", "머더미스터리"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("game_id", models.PositiveIntegerField(verbose_name="게임 ID")),
                ("game_name", models.CharField(max_length=200, verbose_name="게임명")),
                (
                    "play_time",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="플레이 시간(분)"
                    ),
                ),
                (
                    "players",
                    models.CharField(blank=True, max_length=20, verbose_name="인원"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planner.plannersession",
                        verbose_name="플래너 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "플래너 아이템",
                "db_table": "planner_item",
                "ordering": ["order"],
            },
        ),
    ]
